
class PacejkaModel:
    epsilon: float
    FITTYP: int 
    LONGVL: float
    VXLOW: float
    UNLOADED_RADIUS: float
    WIDTH: float
    ASPECT_RATIO: float
    RIM_RADIUS: float
    INFLPRES: float
    NOMPRES: float
    FNOMIN: float
    VERTICAL_STIFFNESS: float
    BREFF: float
    DREFF: float
    FREFF: float
    Q_RE0: float
    Q_V1: float
    Q_V2: float
    Q_FZ2: float
    Q_FCX: float
    Q_FCY: float
    Q_CAM: float
    PFZ1: float
    BOTTOM_OFFST: float
    BOTTOM_STIFF: float
    LONGITUDINAL_STIFFNESS: float
    LATERAL_STIFFNESS: float
    Q_BVX: float
    Q_BVT: float
    PCFX1: float
    PCFX2: float
    PCFX3: float
    PCFY1: float    
    PCFY2: float
    PCFY3: float
    PCMZ1: float
    Q_RA1: float
    Q_RA2: float
    Q_RB1: float
    Q_RB2: float
    PRESMIN: float
    PRESMAX: float
    FZMIN: float
    FZMAX: float
    KPUMIN: float
    KPUMAX: float
    ALPMIN: float
    ALPMAX: float
    CAMMIN: float
    CAMMAX: float
    LFZO: float
    LCX: float
    LMUX: float
    LEX: float
    LKX: float
    LHX: float
    LVX: float
    LCY: float
    LMUY: float
    LEY: float
    LKY: float
    LHY: float
    LVY: float
    LTR: float
    LRES: float
    LXAL: float
    LYKA: float
    LVYKA: float
    LS: float
    LKYC: float
    LKZC: float
    LVMX: float
    LMX: float
    LMY: float
    LMP: float
    PCX1: float
    PDX1: float
    PDX2: float
    PDX3: float
    PEX1: float
    PEX2: float
    PEX3: float
    PEX4: float
    PKX1: float
    PKX2: float
    PKX3: float
    PHX1: float
    PHX2: float
    PVX1: float
    PVX2: float
    PPX1: float
    PPX2: float
    PPX3: float
    PPX4: float
    RBX1: float
    RBX2: float
    RBX3: float
    RCX1: float
    REX1: float
    REX2: float
    RHX1: float
    LMUV: float
    QSX1: float
    QSX2: float
    QSX3: float
    QSX4: float
    QSX5: float
    QSX6: float
    QSX7: float
    QSX8: float
    QSX9: float
    QSX10: float
    QSX11: float
    QSX12: float
    QSX13: float
    QSX14: float
    PPMX1: float
    PCY1: float
    PDY1: float
    PDY2: float
    PDY3: float
    PEY1: float
    PEY2: float
    PEY3: float
    PEY4: float
    PEY5: float
    PKY1: float
    PKY2: float    
    PKY3: float
    PKY4: float
    PKY5: float
    PKY6: float
    PKY7: float
    PHY1: float
    PHY2: float
    PVY1: float
    PVY2: float
    PVY3: float
    PVY4: float
    PPY1: float
    PPY2: float
    PPY3: float
    PPY4: float
    PPY5: float
    RBY1: float
    RBY2: float
    RBY3: float
    RBY4: float
    RCY1: float
    REY1: float
    REY2: float
    RHY1: float
    RHY2: float
    RVY1: float
    RVY2: float
    RVY3: float
    RVY4: float
    RVY5: float
    RVY6: float
    QSY1: float
    QSY2: float
    QSY3: float
    QSY4: float
    QSY5: float
    QSY6: float
    QSY7: float
    QSY8: float
    QBZ1: float
    QBZ2: float
    QBZ3: float
    QBZ4: float
    QBZ5: float
    QBZ9: float
    QBZ10: float
    QCZ1: float
    QDZ1: float
    QDZ2: float
    QDZ3: float
    QDZ4: float    
    QDZ6: float
    QDZ7: float
    QDZ8: float
    QDZ9: float
    QDZ10: float
    QDZ11: float
    QEZ1: float
    QEZ2: float
    QEZ3: float
    QEZ4: float
    QEZ5: float
    QHZ1: float
    QHZ2: float
    QHZ3: float
    QHZ4: float
    PPZ1: float
    PPZ2: float
    SSZ1: float
    SSZ2: float
    SSZ3: float
    SSZ4: float
    PDXP1: float
    PDXP2: float
    PDXP3: float
    PKYP1: float
    PDYP1: float
    PDYP2: float
    PDYP3: float
    PDYP4: float
    PHYP1: float
    PHYP2: float
    PHYP3: float
    PHYP4: float
    PECP1: float
    PECP2: float
    QDTP1: float
    QCRP1: float
    QCRP2: float
    QBRP1: float
    QDRP1: float
    Q_FCY2: float
    Q_CAM1: float
    Q_CAM2: float
    Q_CAM3: float
    LMUV: float
    Q_FYS1: float
    Q_FYS2: float
    Q_FYS3: float
    Q_FYS1 = 0.0
    Q_FYS2 = 0.0
    Q_FYS3 = 0.0

    # TireMFModel Solver for Magic Formula 5.2, 6.1 and 6.2 Tyre Models
    def __init__(self, tire_coefficients: dict) -> None:
        # Parameters not specified in the TIR file
        # Used to avoid low speed singularity
        self.epsilon = 1e-6  # [Eqn (4.E6a) Page 178 - Book]

        for key, value in tire_coefficients.items():
            setattr(self, key, value)