[package]
name = "pacejka_rs"
version = "0.1.0"
edition = "2021"


[lib]
name = "pacejka_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
numpy = "0.23.0"
bincode = "1.3.3"
serde = {version = "1.0", features = ["derive"]}
nalgebra = "0.33.2"